# .air.toml

root = "."
tmp_dir = "tmp"

[build]
# The command to build the Go application.
# Build the main package located in the ./src directory.
cmd = "go build -buildvcs=false -o ./tmp/main ./src"
# The directory where the source code is located.
exclude_dir = ["tmp"]
include_dir = ["src"]
# The file extensions to watch for changes.
include_ext = ["go", "mod", "sum"]
# The binary to run. This should match the output of the build command.
bin = "tmp/main"
# The command to start the application.
args_bin = []

[log]
# The color scheme for the logs.
time = true
color = true

[misc]
# If true, Air will kill the server when the application is reloaded.
clean_on_exit = true

[build.env]
# Define environment variables for the build process if needed.
# For example: CGO_ENABLED = "0"
